### ISSUE TITLE
Github urls out of date since new organization migration

### ISSUE THREAD

**Issue by jpmcb** [bytecodealliance/wasmtime.dev#2]
Noticed that several of the Github urls still point to **https://github.com/CraneStation/**

It appears that [this PR address the issue](https://github.com/bytecodealliance/wasmtime.dev/pull/1)

Dose this require any additional work?
Thanks!

**Comment by tschneidereit** [comment]
It does not require additional work, beyond just merging that PR, which I at long last just did :)
